services:
  my-node-app:
    build: .
    container_name: my-node-app
    restart: always
    env_file:
      - .env-back.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env-db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: